name: Publish docs
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install project dependencies
        run: yarn install --pure-lockfile
      - name: Update gh-pages
        run: |
          yarn deploy-docs -m 'chore: build docs'
